In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "../data/raw/DataCoSupplyChainDataset.csv",
    encoding="latin1"
)

print(df.shape)

print(df.shape)

(180519, 53)
(180519, 53)

In [3]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [4]:
df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

In [6]:
for i, col in enumerate(df.columns, start=1):
    print(i, ":", col)

1 : Type
2 : Days for shipping (real)
3 : Days for shipment (scheduled)
4 : Benefit per order
5 : Sales per customer
6 : Delivery Status
7 : Late_delivery_risk
8 : Category Id
9 : Category Name
10 : Customer City
11 : Customer Country
12 : Customer Email
13 : Customer Fname
14 : Customer Id
15 : Customer Lname
16 : Customer Password
17 : Customer Segment
18 : Customer State
19 : Customer Street
20 : Customer Zipcode
21 : Department Id
22 : Department Name
23 : Latitude
24 : Longitude
25 : Market
26 : Order City
27 : Order Country
28 : Order Customer Id
29 : order date (DateOrders)
30 : Order Id
31 : Order Item Cardprod Id
32 : Order Item Discount
33 : Order Item Discount Rate
34 : Order Item Id
35 : Order Item Product Price
36 : Order Item Profit Ratio
37 : Order Item Quantity
38 : Sales
39 : Order Item Total
40 : Order Profit Per Order
41 : Order Region
42 : Order State
43 : Order Status
44 : Order Zipcode
45 : Product Card Id
46 : Product Category Id
47 : Product Description
48 : Product Image
49 : Product Name
50 : Product Price
51 : Product Status
52 : shipping date (DateOrders)
53 : Shipping Mode

In [7]:
missing = df.isnull().sum()

missing[missing > 0]

Customer Lname              8
Customer Zipcode            3
Order Zipcode          155679
Product Description    180519
dtype: int64

In [8]:
missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_report[missing_report["Missing_Count"] > 0]

                     Missing_Count  Missing_Percentage
Customer Lname                   8            0.004432
Customer Zipcode                 3            0.001662
Order Zipcode               155679           86.239676
Product Description         180519          100.000000

In [9]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [10]:
print("Shipping Modes:")
print(df["Shipping Mode"].value_counts())

print("\nDelivery Status:")
print(df["Delivery Status"].value_counts())

print("\nLate Delivery Risk:")
print(df["Late_delivery_risk"].value_counts())

Shipping Modes:
Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

Delivery Status:
Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

Late Delivery Risk:
Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "../data/raw/DataCoSupplyChainDataset.csv",
    encoding="latin1"
)

print("Original shape:", df.shape)

Original shape: (180519, 53)

In [2]:
clean_df = df.copy()

print("Cleaning copy created:", clean_df.shape)

Cleaning copy created: (180519, 53)

In [3]:
columns_to_remove = [
    "Customer Email",
    "Customer Fname",
    "Customer Lname",
    "Customer Password",
    "Customer Street",
    "Customer Zipcode"
]

clean_df = clean_df.drop(
    columns=columns_to_remove,
    errors="ignore"
)

print("Shape after removing customer PII:", clean_df.shape)

Shape after removing customer PII: (180519, 47)

In [4]:
columns_to_remove = [
    "Product Description",
    "Order Zipcode"
]

clean_df = clean_df.drop(
    columns=columns_to_remove,
    errors="ignore"
)

print("Shape after removing unusable columns:", clean_df.shape)

Shape after removing unusable columns: (180519, 45)

In [5]:
missing = clean_df.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

In [6]:
date_columns = [
    col for col in clean_df.columns
    if "date" in col.lower()
]

print("Date columns:")
for col in date_columns:
    print("-", col)

Date columns:
- order date (DateOrders)
- shipping date (DateOrders)

In [7]:
date_columns = [
    "order date (DateOrders)",
    "shipping date (DateOrders)"
]

for col in date_columns:
    clean_df[col] = pd.to_datetime(
        clean_df[col],
        errors="coerce"
    )

print(clean_df[date_columns].dtypes)

order date (DateOrders)       datetime64[us]
shipping date (DateOrders)    datetime64[us]
dtype: object

In [8]:
for col in date_columns:
    print(
        col,
        "missing after conversion:",
        clean_df[col].isna().sum()
    )

order date (DateOrders) missing after conversion: 0
shipping date (DateOrders) missing after conversion: 0

In [9]:
clean_df.columns = (
    clean_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace("-", "_", regex=False)
)

print(clean_df.columns.tolist())

['type', 'days_for_shipping_real', 'days_for_shipment_scheduled', 'benefit_per_order', 'sales_per_customer', 'delivery_status', 'late_delivery_risk', 'category_id', 'category_name', 'customer_city', 'customer_country', 'customer_id', 'customer_segment', 'customer_state', 'department_id', 'department_name', 'latitude', 'longitude', 'market', 'order_city', 'order_country', 'order_customer_id', 'order_date_dateorders', 'order_id', 'order_item_cardprod_id', 'order_item_discount', 'order_item_discount_rate', 'order_item_id', 'order_item_product_price', 'order_item_profit_ratio', 'order_item_quantity', 'sales', 'order_item_total', 'order_profit_per_order', 'order_region', 'order_state', 'order_status', 'product_card_id', 'product_category_id', 'product_image', 'product_name', 'product_price', 'product_status', 'shipping_date_dateorders', 'shipping_mode']

In [10]:
print("Quantity:")
print(clean_df["order_item_quantity"].describe())

print("\nNegative quantities:")
print((clean_df["order_item_quantity"] < 0).sum())

Quantity:
count    180519.000000
mean          2.127638
std           1.453451
min           1.000000
25%           1.000000
50%           1.000000
75%           3.000000
max           5.000000
Name: order_item_quantity, dtype: float64

Negative quantities:
0

In [11]:
print("Product Price:")
print(clean_df["product_price"].describe())

print("\nNegative product prices:")
print((clean_df["product_price"] < 0).sum())

Product Price:
count    180519.000000
mean        141.232550
std         139.732492
min           9.990000
25%          50.000000
50%          59.990002
75%         199.990005
max        1999.989990
Name: product_price, dtype: float64

Negative product prices:
0

In [12]:
print("Discount:")
print(clean_df["order_item_discount"].describe())

print("\nNegative discounts:")
print((clean_df["order_item_discount"] < 0).sum())

Discount:
count    180519.000000
mean         20.664741
std          21.800901
min           0.000000
25%           5.400000
50%          14.000000
75%          29.990000
max         500.000000
Name: order_item_discount, dtype: float64

Negative discounts:
0

In [13]:
print("Scheduled shipping days:")
print(clean_df["days_for_shipment_scheduled"].describe())

print("\nInvalid scheduled days:")
print((clean_df["days_for_shipment_scheduled"] <= 0).sum())

Scheduled shipping days:
count    180519.000000
mean          2.931847
std           1.374449
min           0.000000
25%           2.000000
50%           4.000000
75%           4.000000
max           4.000000
Name: days_for_shipment_scheduled, dtype: float64

Invalid scheduled days:
9737

In [14]:
print("Actual shipping days:")
print(clean_df["days_for_shipping_real"].describe())

print("\nInvalid actual shipping days:")
print((clean_df["days_for_shipping_real"] <= 0).sum())

Actual shipping days:
count    180519.000000
mean          3.497654
std           1.623722
min           0.000000
25%           2.000000
50%           3.000000
75%           5.000000
max           6.000000
Name: days_for_shipping_real, dtype: float64

Invalid actual shipping days:
5080

In [15]:
invalid_dates = (
    clean_df["shipping_date_dateorders"]
    < clean_df["order_date_dateorders"]
)

print("Shipping before order:", invalid_dates.sum())

Shipping before order: 0

In [16]:
print("Order date range:")
print(clean_df["order_date_dateorders"].min())
print(clean_df["order_date_dateorders"].max())

print("\nShipping date range:")
print(clean_df["shipping_date_dateorders"].min())
print(clean_df["shipping_date_dateorders"].max())

Order date range:
2015-01-01 00:00:00
2018-01-31 23:38:00

Shipping date range:
2015-01-03 00:00:00
2018-02-06 22:14:00

In [17]:
clean_df["shipping_mode"].value_counts()

shipping_mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

In [18]:
clean_df["delivery_status"].value_counts()

delivery_status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

In [19]:
clean_df["market"].value_counts()

market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

In [20]:
clean_df["customer_segment"].value_counts()

customer_segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

In [21]:
target_counts = clean_df["late_delivery_risk"].value_counts()

print(target_counts)

print("\nPercentage:")
print(
    clean_df["late_delivery_risk"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

Percentage:
late_delivery_risk
1    54.83
0    45.17
Name: proportion, dtype: float64

In [22]:
clean_df.to_csv(
    "../data/cleaned/supply_chain_clean.csv",
    index=False
)

print("Processed file saved successfully!")
print("Shape:", clean_df.shape)

Processed file saved successfully!
Shape: (180519, 45)